tap "d12frosted/emacs-plus"
brew "emacs-plus", args: ["without-spacemacs-icon"]

cask "karabiner-elements"
tap "yqrashawn/goku"
brew "yqrashawn/goku/goku"

cask "bitbar"

brew "fish"
cask "hyper"
cask "phoenix"

brew "pass"
brew "pass-otp"

brew "git"
brew "hub"
brew "asdf"
brew "grip"
brew "buku"
brew "trash"
brew "gnupg"
brew "direnv"
brew "ripgrep"
