#!/usr/bin/env sh
set -euf

$(pass backup.env)

rm -rf ~/.logseq-backup
cp -R /Users/david/Library/Mobile\ Documents/iCloud~com~logseq~logseq/Documents/ ~/.logseq-backup

LOGFILE="${HOME}/.backup.log"

if [ ! -e "$LOGFILE" ] ; then
    touch "$LOGFILE"
fi

#echo "Beginning backup at $(date)" >> "$LOGFILE"

# TODO consider specifying includes rather than excludes

restic backup ~                            \
    --exclude="**/node_modules"            \
    --exclude="**/.log"                    \
    --exclude="**/target/release"          \
    --exclude="**/straight/repos"          \
    --exclude="**/cache/eln"               \
    --exclude="**/.next/cache"             \
    --exclude="**/.arduino"                \
    --exclude="**/*.elc"                   \
    --exclude="${HOME}/desk"               \
    --exclude="${HOME}/files"              \
    --exclude="${HOME}/mail"               \
    --exclude="${HOME}/.ssh"               \
    --exclude="${HOME}/.sbt"               \
    --exclude="${HOME}/.sdkman"            \
    --exclude="${HOME}/.gnupg"             \
    --exclude="${HOME}/.config/emacs*"     \
    --exclude="${HOME}/.config/yarn"       \
    --exclude="${HOME}/.npm"               \
    --exclude="${HOME}/.ollama"            \
    --exclude="${HOME}/.pnpm-store"        \
    --exclude="${HOME}/.quicklisp"         \
    --exclude="${HOME}/.tmux"              \
    --exclude="${HOME}/.vscode"            \
    --exclude="${HOME}/.gem"               \
    --exclude="${HOME}/.bun"               \
    --exclude="${HOME}/.degit"             \
    --exclude="${HOME}/.orbstack"          \
    --exclude="${HOME}/.giget"             \
    --exclude="${HOME}/.pnpm-bin"          \
    --exclude="${HOME}/.pnpm-state"        \
    --exclude="${HOME}/.tea"               \
    --exclude="${HOME}/.yarn"              \
    --exclude="${HOME}/.fly"               \
    --exclude="${HOME}/.asdf"              \
    --exclude="${HOME}/.local"             \
    --exclude="${HOME}/.cache"             \
    --exclude="${HOME}/.gradle"            \
    --exclude="${HOME}/.bundle"            \
    --exclude="${HOME}/.stack"             \
    --exclude="${HOME}/.cargo"             \
    --exclude="${HOME}/.rustup"            \
    --exclude="${HOME}/.Trash"             \
    --exclude="${HOME}/Library"            \
    --exclude="${HOME}/Desktop"            \
    --exclude="${HOME}/Documents"          \
    --exclude="${HOME}/Applications"       \
    --exclude="${HOME}/Pictures"           \
    --exclude="${HOME}/Public"             \
    --exclude="${HOME}/google-cloud-sdk"   \
    --exclude="${HOME}/Movies"             \
    --exclude="${HOME}/Music"              \
    --exclude="${HOME}/Tresors"            \
    --exclude="${HOME}/OrbStack"           \
    --exclude="${HOME}/metabase"           \
    --exclude="${HOME}/src/work"           \
    --exclude="${HOME}/src/clones"         \
#    | tee -a "$LOGFILE"

#printf "\n*******************************************************\n\n" >> "$LOGFILE"
