#!/usr/bin/env sh

BASE_BRANCH=${1:-$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')}
CURRENT_BRANCH=$(git branch --show-current)

{ git log --name-status "$BASE_BRANCH".."$CURRENT_BRANCH"; git status --short; }  | grep -E '^\s*[AM]\b' | sed -E 's/^[[:space:]]*[A-Z][[:space:]]*//'
