#!/usr/bin/env sh

EMACS=${EMACS:-emacs}
EMACSCLIENT=${EMACSCLIENT:-emacsclient}

PATH_TO_OPEN=${1:-.}

if [ "$(ps -ax | rg -c emacs)" -gt 1 ]; then
    if [ "$($EMACSCLIENT -e '(length (frame-list))')" -gt 1 ]; then
        $EMACSCLIENT -n "$PATH_TO_OPEN"
    else
        $EMACSCLIENT -nc "$PATH_TO_OPEN"
    fi
else
    $EMACS --daemon; $EMACSCLIENT -nc "$PATH_TO_OPEN"
fi
