#!/usr/bin/env sh

if test ! -t 0; then
    STDIN=$(cat)
    BUFFER_NAME="*stdin-$(date "+%H:%M:%S")*"
    emacsclient -n -a '' --eval "(let ((b (generate-new-buffer \"$BUFFER_NAME\"))) (switch-to-buffer b) (insert \"$STDIN\"))" >/dev/null
    echo "piped to emacs buffer $BUFFER_NAME"
    [ "$(uname)" = "Darwin" ] && osascript -e 'tell application "emacs" to activate first window'
else
    echo "no stdin"
fi
