#!/usr/bin/env sh

if [ -z "$NOTES_DIR" ]; then
    echo "\$NOTES_DIR not set"
    exit 1
fi

if [ ! -d "$NOTES_DIR" ]; then
    echo "\$NOTES_DIR $NOTES_DIR doesn't exist"
    exit 1
fi

filename="$(date +%Y-%m-%d).md"

filepath="$NOTES_DIR/$filename"

if [ ! -e "$filepath" ]; then
    echo "creating"
    touch "$filepath"
fi

e "$filepath"
